### ISSUE TITLE
Figure Wallet redirects to test

### ISSUE THREAD

**Issue by jarrydallison** [provenance-io/walletconnect-js#136]
## Summary of Bug

Selecting Figure Wallet redirects to test

## Version

Current

## Steps to Reproduce

Attempt to select Figure Wallet in prod, it redirects to test. The issue exists in the consts folder > urls.ts

![Screen Shot 2022-11-15 at 12 06 05 PM](https://user-images.githubusercontent.com/90670725/202004312-d31e16eb-36f2-477f-b02a-d919cdb2b955.png)

The FIGURE_WEB_WALLET_URL needs to be updated to point to either test or prod depending on the environment.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by VigM-Figure** [comment]
Will add two new wallets, figure_web_test and figure_mobile_test.  These will remain dev wallets, the production figure wallets will be moved out of dev.  It will be on the dApp to tell the QRCodeModal which wallets it wants to render as options for the user.
