### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by jarrydallison** [provenance-io/walletconnect-js#154]
## Summary

Update README

## Problem Definition

Version 2.1.2 introduced a change that, for whatever reason, requires react-scripts 5+. This issue updates the README to describe this issue and inform users of the requirement.

## Proposal

Update README
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by VigM-Figure** [comment]
This was a result of a missing plugin within babel.config.js, it will be fixed with the release of 3.0.0

**Comment by VigM-Figure** [comment]
With the release of 3.0.0 this should no longer be an issue.  If you see anything missing from the readme please make a new issue.  Thanks!
